"use strict";
console.log("Hey Adil, I have started learning TYPESCRIPT");
var name1 = "MUHAMMAD ADIL";
console.log(name1);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var addition_all = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log(addition_all);
var sub_all = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log(sub_all);
var multip_all = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log(multip_all);
var div_2 = num10 / num5;
console.log(div_2);
var check_dmas = div_2 * addition_all + sub_all - multip_all;
console.log(check_dmas);
